### ISSUE TITLE
Postpone datafolder/global variables creation to first use

### ISSUE THREAD

**Issue by t-b** [tango-controls/igorpro-binding#1]
Currently the tango xop creates the following globals on igor start:

```
root:tango:
root:tango:common
root:tango:common:error
root:tango:common:desc
root:tango:common:origin
root:tango:common:reason
```

This is a bit annoying if you don't use the tango xop in that igor session at all as it marks the experiment as modified.

It would be nicer if the creation would be postponed to the first use of one of the tango XOP functions.

**Comment by nleclercq** [comment]
Well, in fact, this error info is totally useless. It's there for historical reasons and can be safely removed. That's what I've done. The error code itself (i.e. root:tango:common:error) is still used but will be created when needed.

However, the binding prefs are still loaded and displayed in Igor's history at startup. Is it also a problem for you?

**Comment by nleclercq** [comment]
@t-b Did you see my previous question ?

**Comment by t-b** [comment]
@nleclercq Sorry for the late reply. I've tested latest master and no more useless globals from the tango XOP. Hurray!

Regarding the bindings prefs we don't use that. But just FYI there is `XOPNotice2` which allows you to *not* mark the experiment as modified when writing into the history.

**Comment by nleclercq** [comment]
Thomas, Thanks for the `XOPNotice2` trick. Will apply it asap.

**Comment by t-b** [comment]
Closing as resolved.
