### ISSUE TITLE
Code generator: possible functions name conflict 

### ISSUE THREAD

**Issue by nleclercq** [tango-controls/igorpro-binding#3]
Problem:
Let a Tango device with a **GetConfigList** command and a **configList** attribute.
When the user generates an Igor Pro interface for this device, our code generator naming scheme will create **GetConfigList(dest_path, [tms, qlt])** for the read part of the attribute and  **GetConfigList(out_wave_path)** for the command - which is a clear naming clash. 

Possible solution:
In such a case, add an **Exec** prefix to the command signature: **ExecGetConfigList(out_wave_path)**.

**Comment by t-b** [comment]
@nleclercq Or you could always append a suffix a la `Attr`/`Cmd` to indicate if it is a command or attribute. In IP8 the object name limit is 255 characters so there is no need to keep the names really short.

**Comment by nleclercq** [comment]
You're right. Unfortunately we have some code in production making use of the current naming scheme. Users might have to regenerate a device interface in case its Tango interface evolves and they certainly would like their code to continue to work properly.   

I've done the following: use **GetAttr**, **SetAttr** or **Exec** prefix in case of conflict and print a warning in Igor's history to let the user know about what has been done. 

Can I close this issue ?

**Comment by nleclercq** [comment]
I finally changed the functions naming scheme but also added a backward compatibility option to the code generator.
